---
matrix:
  include:
    - language: node_js
      name: "Front-end"
      node_js:
        - 10
      cache:
        yarn: true
        directories:
          - node_modules
      before_install:
        - cd frontend
      script:
        - yarn build
        
    - language: node_js
      name: "Front-end"
      arch: arm64
      node_js:
        - 10
      cache:
        yarn: true
        directories:
          - node_modules
      before_install:
        - cd frontend
      script:
        - yarn build
